// One-shot batch script (task 19f), run by a scheduled GitHub Actions
// workflow (../../.github/workflows/mtproto_archive.yml) on `schedule` +
// `workflow_dispatch` only. Replaces the always-on Express sidecar
// (src/index.ts, removed this slice) that used to run as a fourth s6
// service inside the Rails container (docker/rootfs/etc/services.d/
// mtproto-worker/, also removed).
//
// Rails no longer holds an HTTP client to a live worker process — that was
// Anthropic::MtprotoArchiveService, removed alongside AnthropicMtprotoArchiveJob's
// cron scan (see ../../handover.md Task 19f). Instead the interface is now
// entirely token-authed HTTP against Rails' own /api surface:
//   1. GET  {ZEALOT_URL}/api/mtproto_archive/candidates?token=...
//      -> releases old/large enough to archive, each with a short-lived
//         signed download URL (see Api::MtprotoArchiveController).
//   2. Download each candidate straight from that signed URL (never touches
//      Rails' storage credentials — only whatever ReleaseStorage's adapter
//      already made public via the signed URL).
//   3. Archive it into Telegram via the same MtprotoClient this worker
//      always used (mtproto_client.ts, unchanged).
//   4. POST {ZEALOT_URL}/api/mtproto_archive/{release_id}/complete with the
//      encoded location, so Rails records mtproto_archived_location/_at.
//
// Best-effort per candidate, same posture the old cron job had: one
// candidate failing (bad download, Telegram error, Rails rejecting the
// completion report) is logged and the run moves on to the next one rather
// than aborting the whole batch. The process exits non-zero only if any
// candidate failed (so the Action run is visibly marked failed and worth a
// look) or if a fatal, run-wide error occurs (can't reach Rails at all,
// missing env vars).
//
// Required env vars:
//   ZEALOT_URL                 - e.g. https://zealot.example.com (no trailing slash)
//   ZEALOT_ADMIN_TOKEN         - an admin user's API token (Zealot's ?token= auth)
//   TELEGRAM_API_ID            - from my.telegram.org, our own app
//   TELEGRAM_API_HASH
//   TELEGRAM_SESSION_STRING    - pre-authenticated StringSession for the
//                                 archive account (generated once, offline,
//                                 by an operator — never generated by this
//                                 script itself)
//   TELEGRAM_ARCHIVE_CHAT_ID   - private chat/channel we control that
//                                 receives archived artifacts

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { randomUUID } from 'node:crypto';
import { MtprotoClient, encodeLocation } from './mtproto_client.js';

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`missing required env var ${name}`);
  return value;
}

interface Candidate {
  release_id: number;
  key: string;
  download_url: string | null;
  compressed_size: number | null;
  created_at: string;
}

const zealotUrl = requireEnv('ZEALOT_URL').replace(/\/+$/, '');
const adminToken = requireEnv('ZEALOT_ADMIN_TOKEN');

const client = new MtprotoClient({
  apiId: Number(requireEnv('TELEGRAM_API_ID')),
  apiHash: requireEnv('TELEGRAM_API_HASH'),
  sessionString: requireEnv('TELEGRAM_SESSION_STRING'),
  archiveChatId: requireEnv('TELEGRAM_ARCHIVE_CHAT_ID'),
});

function withToken(pathAndQuery: string): string {
  const separator = pathAndQuery.includes('?') ? '&' : '?';
  return `${zealotUrl}${pathAndQuery}${separator}token=${encodeURIComponent(adminToken)}`;
}

async function fetchCandidates(): Promise<Candidate[]> {
  const res = await fetch(withToken('/api/mtproto_archive/candidates'));
  if (!res.ok) {
    throw new Error(`GET /api/mtproto_archive/candidates failed: ${res.status} ${await res.text()}`);
  }
  const body = (await res.json()) as { candidates: Candidate[] };
  return body.candidates;
}

async function reportComplete(releaseId: number, location: string): Promise<void> {
  const res = await fetch(withToken(`/api/mtproto_archive/${releaseId}/complete`), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ location }),
  });
  if (!res.ok) {
    throw new Error(`POST /api/mtproto_archive/${releaseId}/complete failed: ${res.status} ${await res.text()}`);
  }
}

// Streams straight to a tmp file rather than buffering in memory — these
// are release artifacts (compressed .apks), which can be large.
async function downloadToTmp(url: string): Promise<string> {
  const tmpPath = path.join(os.tmpdir(), `mtproto-archive-${randomUUID()}`);
  const res = await fetch(url);
  if (!res.ok || !res.body) {
    throw new Error(`download failed: ${res.status}`);
  }
  await pipeline(Readable.fromWeb(res.body as Parameters<typeof Readable.fromWeb>[0]), fs.createWriteStream(tmpPath));
  return tmpPath;
}

async function archiveOne(candidate: Candidate): Promise<void> {
  if (!candidate.download_url) {
    console.warn(`release ${candidate.release_id}: no download_url, skipping`);
    return;
  }

  const tmpPath = await downloadToTmp(candidate.download_url);
  try {
    const location = await client.archive(tmpPath, candidate.key);
    const encoded = encodeLocation(location);
    await reportComplete(candidate.release_id, encoded);
    console.log(`release ${candidate.release_id}: archived -> ${encoded}`);
  } finally {
    await fs.promises.unlink(tmpPath).catch(() => {});
  }
}

async function main(): Promise<void> {
  const candidates = await fetchCandidates();
  console.log(`${candidates.length} candidate(s) to archive`);

  let failures = 0;
  for (const candidate of candidates) {
    try {
      await archiveOne(candidate);
    } catch (err) {
      failures += 1;
      console.error(`release ${candidate.release_id}: failed - ${(err as Error).message}`);
    }
  }

  if (failures > 0) {
    console.error(`${failures} of ${candidates.length} candidate(s) failed`);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(`fatal: ${(err as Error).message}`);
  process.exitCode = 1;
});
