// HTTP sidecar exposing archive/retrieve over Telegram MTProto cold storage
// to the Rails app (Anthropic::MtprotoArchiveService). Not exposed
// publicly — bind to a private network / internal Render service, and gate
// every request on MTPROTO_WORKER_SHARED_SECRET.
//
// Required env vars:
//   TELEGRAM_API_ID            - from my.telegram.org, our own app
//   TELEGRAM_API_HASH
//   TELEGRAM_SESSION_STRING    - pre-authenticated StringSession for the
//                                 archive account (generated once, offline,
//                                 by an operator — never generated by this
//                                 worker itself)
//   TELEGRAM_ARCHIVE_CHAT_ID   - private chat/channel we control that
//                                 receives archived artifacts
//   MTPROTO_WORKER_SHARED_SECRET - bearer token Rails must send
//   PORT                       - default 8081

import express, { type Request, type Response, type NextFunction } from 'express';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { MtprotoClient, encodeLocation, decodeLocation } from './mtproto_client.js';

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`missing required env var ${name}`);
  return value;
}

const sharedSecret = requireEnv('MTPROTO_WORKER_SHARED_SECRET');

const client = new MtprotoClient({
  apiId: Number(requireEnv('TELEGRAM_API_ID')),
  apiHash: requireEnv('TELEGRAM_API_HASH'),
  sessionString: requireEnv('TELEGRAM_SESSION_STRING'),
  archiveChatId: requireEnv('TELEGRAM_ARCHIVE_CHAT_ID'),
});

const app = express();

function auth(req: Request, res: Response, next: NextFunction): void {
  const header = req.header('authorization') || '';
  const token = header.startsWith('Bearer ') ? header.slice('Bearer '.length) : '';
  if (token !== sharedSecret) {
    res.status(401).json({ error: 'unauthorized' });
    return;
  }
  next();
}

app.get('/healthz', (_req, res) => res.json({ ok: true }));

app.post('/archive', auth, express.raw({ type: '*/*', limit: '5gb' }), async (req, res) => {
  const archiveKey = req.header('x-archive-key');
  if (!archiveKey) {
    res.status(400).json({ error: 'missing X-Archive-Key header' });
    return;
  }

  const tmpPath = path.join(os.tmpdir(), `mtproto-archive-${randomUUID()}`);
  try {
    await fs.promises.writeFile(tmpPath, req.body as Buffer);
    const location = await client.archive(tmpPath, archiveKey);
    res.json({ location: encodeLocation(location) });
  } catch (err) {
    res.status(502).json({ error: (err as Error).message });
  } finally {
    fs.promises.unlink(tmpPath).catch(() => {});
  }
});

app.get('/retrieve', auth, async (req, res) => {
  const raw = req.query.location;
  if (typeof raw !== 'string') {
    res.status(400).json({ error: 'missing location query param' });
    return;
  }

  const tmpPath = path.join(os.tmpdir(), `mtproto-retrieve-${randomUUID()}`);
  try {
    const location = decodeLocation(raw);
    const found = await client.retrieve(location, tmpPath);
    if (!found) {
      res.status(404).json({ error: 'archived message not found' });
      return;
    }
    res.setHeader('Content-Type', 'application/octet-stream');
    fs.createReadStream(tmpPath)
      .on('close', () => fs.promises.unlink(tmpPath).catch(() => {}))
      .pipe(res);
  } catch (err) {
    res.status(502).json({ error: (err as Error).message });
  }
});

const port = Number(process.env.PORT || 8081);

client
  .connect()
  .then(() => {
    app.listen(port, () => {
      // eslint-disable-next-line no-console
      console.log(`mtproto-worker listening on :${port}`);
    });
  })
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error('mtproto-worker failed to connect to Telegram:', err);
    process.exit(1);
  });
