# frozen_string_literal: true

class WebHook < ApplicationRecord
  # Z-P19: the signing secret is a Standard Webhooks secret (whsec_...). It is generated by the app, never
  # typed by the owner, and encrypted at rest like every other secret here.
  encrypts :signing_secret

  has_and_belongs_to_many :channels, dependent: :destroy

  delegate :count, to: :channels, prefix: true

  validates :channel_id, :url, presence: true
  validates :body, jb: true

  # Whether deliveries carry Standard Webhooks signature headers. A hook with no secret sends unsigned, the
  # way it always has.
  def signed?
    signing_secret.present?
  end

  # Generates and stores a fresh secret, replacing any previous one. Returns the new secret so the owner can
  # copy it once — it is never shown again in full.
  def rotate_signing_secret!
    secret = "whsec_#{SecureRandom.base64(24)}"
    update!(signing_secret: secret, signing_secret_set_at: Time.current)
    secret
  end
end

